// <auto-generated />
using Anevo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Anevo.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20231028142637_ChangeTablesNames")]
    partial class ChangeTablesNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Anevo.Models.Tables.Groups.SG_001", b =>
                {
                    b.Property<int>("SG001_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SG001_Id"));

                    b.Property<int>("SG001_GroupNr")
                        .HasColumnType("int");

                    b.Property<int>("SU001_Id_User")
                        .HasColumnType("int");

                    b.HasKey("SG001_Id");

                    b.ToTable("SG_001");
                });

            modelBuilder.Entity("Anevo.Models.Tables.Groups.SG_010", b =>
                {
                    b.Property<int>("SG010_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SG010_Id"));

                    b.Property<int>("SG010_Group_Nr")
                        .HasColumnType("int");

                    b.Property<string>("SU010_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SG010_Id");

                    b.ToTable("SG_010");
                });

            modelBuilder.Entity("Anevo.Models.Tables.User.SU_001", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SU_001");
                });
#pragma warning restore 612, 618
        }
    }
}
